'use strict';
// Local-only WebGL world test. Model decoding and mod loading happen in Python.
const canvas=document.getElementById('world'),menu=document.getElementById('menu'),loading=document.getElementById('loading');
const gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});
const sub=(a,b)=>a.map((v,i)=>v-b[i]);
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const norm=a=>{const l=Math.hypot(...a)||1;return a.map(v=>v/l);};
function multiply(a,b){const c=new Float32Array(16);for(let j=0;j<4;j++)for(let i=0;i<4;i++)for(let k=0;k<4;k++)c[j*4+i]+=a[k*4+i]*b[j*4+k];return c;}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function lookAt(eye,target){const z=norm(sub(eye,target)),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
function makeProgram(){const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,`attribute vec3 position;attribute vec2 uv;attribute vec3 normal;attribute vec4 color;uniform mat4 mvp;uniform vec3 eye;uniform float enhanced;varying vec2 texcoord;varying vec4 tint;varying float distanceToEye;void main(){gl_Position=mvp*vec4(position,1.);texcoord=uv;float light=.6+.4*max(dot(normalize(normal),normalize(vec3(.3,.8,.4))),0.);tint=vec4(mix(color.rgb,max(color.rgb,vec3(.35))*light,enhanced),color.a);distanceToEye=distance(position,eye);}`));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,`precision mediump float;uniform sampler2D image;uniform vec3 sky;uniform float fogDistance;uniform float cutoff;varying vec2 texcoord;varying vec4 tint;varying float distanceToEye;void main(){vec4 c=texture2D(image,texcoord)*tint;if(c.a<cutoff)discard;float fog=smoothstep(fogDistance*.55,fogDistance,distanceToEye);gl_FragColor=vec4(mix(c.rgb,sky,fog),c.a);}`));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
let scene=null,drawBatches=[],textures=[],ready=false,position=[0,15.5,0],yaw=0,pitch=0;
const keys=new Set();let dragging=false,lastX=0,lastY=0;
function resetCamera(){position=scene?scene.spawn.slice():[0,15.5,0];yaw=0;pitch=0;}
function showMenu(show){menu.hidden=!show;for(const id of ['hud','hudButtons','help'])document.getElementById(id).hidden=show;keys.clear();dragging=false;if(show){if(document.pointerLockElement===canvas)document.exitPointerLock();document.getElementById('start').focus();}else canvas.focus();}
function enter(){if(!ready)return;showMenu(false);try{const promise=canvas.requestPointerLock?.();promise?.catch?.(()=>{});}catch(_){/* drag controls remain available */}}
for(const tab of document.querySelectorAll('[data-panel]'))tab.addEventListener('click',()=>{for(const b of document.querySelectorAll('[data-panel]'))b.setAttribute('aria-pressed',String(b===tab));for(const panel of document.querySelectorAll('[data-content]'))panel.hidden=panel.dataset.content!==tab.dataset.panel;});
document.getElementById('start').onclick=enter;
document.getElementById('menuButton').onclick=()=>showMenu(true);
document.getElementById('resetButton').onclick=resetCamera;
async function fullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch(error){loading.textContent='Fullskjerm er ikke tilgjengelig: '+error.message;}}
document.getElementById('fullscreen').onclick=fullscreen;
for(const id of ['fov','scale'])document.getElementById(id).addEventListener('input',()=>document.getElementById(id+'Value').value=document.getElementById(id).value);
window.addEventListener('keydown',event=>{const key=event.key.toLowerCase();if(['input','select','textarea'].includes(event.target.tagName.toLowerCase()))return;if(key==='escape'){if(menu.hidden)showMenu(true);return;}if(key==='m'){menu.hidden?showMenu(true):enter();event.preventDefault();return;}if(!menu.hidden)return;if(['w','a','s','d','q','e','shift','r','f',' '].includes(key)){keys.add(key);event.preventDefault();if(key==='r')resetCamera();if(key==='f')fullscreen();}});
window.addEventListener('keyup',event=>keys.delete(event.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();dragging=false;});
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==canvas&&menu.hidden)showMenu(true);});
canvas.addEventListener('pointerdown',event=>{if(!menu.hidden)return;dragging=true;lastX=event.clientX;lastY=event.clientY;canvas.setPointerCapture(event.pointerId);});
canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
document.addEventListener('mousemove',event=>{if(!menu.hidden)return;let dx=0,dy=0;if(document.pointerLockElement===canvas){dx=event.movementX;dy=event.movementY;}else if(dragging){dx=event.clientX-lastX;dy=event.clientY-lastY;lastX=event.clientX;lastY=event.clientY;}yaw-=dx*.0025;pitch=Math.max(-1.5,Math.min(1.5,pitch-dy*.0025));});
canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();ready=false;showMenu(true);loading.textContent='Grafikkonteksten ble mistet. Last siden på nytt.';loading.classList.add('error');});
async function concurrent(items,callback){let cursor=0;await Promise.all(Array.from({length:Math.min(4,items.length)},async()=>{while(cursor<items.length){const index=cursor++;await callback(items[index],index);}}));}
async function start(){
 if(!gl)throw Error('WebGL er ikke tilgjengelig. Prøv en nettleser med maskinvareakselerasjon.');
 const response=await fetch('/api/scene');if(!response.ok)throw Error('Kunne ikke laste scenen.');scene=await response.json();
 resetCamera();let complete=0;const total=scene.textures.length+scene.batches.length;
 const progress=()=>{loading.textContent=`Forbereder kart og teksturer · ${++complete}/${total}`;};
 await concurrent(scene.textures,async(t,i)=>{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('Kunne ikke laste '+t.key));image.src=t.url;});const texture=gl.createTexture();textures[i]=texture;gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);const repeat=(image.width&(image.width-1))===0&&(image.height&(image.height-1))===0;const modeS=(t.filtering>>8)&15,modeT=(t.filtering>>12)&15;const address=mode=>!repeat?gl.CLAMP_TO_EDGE:mode===2?gl.MIRRORED_REPEAT:mode>=3?gl.CLAMP_TO_EDGE:gl.REPEAT;gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,address(modeS));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,address(modeT));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);if(repeat){gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);}else gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);progress();});
 await concurrent(scene.batches,async(b,i)=>{const response=await fetch(b.url);if(!response.ok)throw Error('Kunne ikke laste geometri.');const bytes=await response.arrayBuffer();if(bytes.byteLength!==b.count*48)throw Error('Ugyldig geometribuffer.');const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(bytes),gl.STATIC_DRAW);drawBatches[i]={...b,buffer};progress();});
 const p=makeProgram();gl.useProgram(p);const uniforms={};for(const name of ['mvp','eye','enhanced','sky','fogDistance','cutoff'])uniforms[name]=gl.getUniformLocation(p,name);gl.uniform1i(gl.getUniformLocation(p,'image'),0);
 const attributes=[['position',3,0],['uv',2,12],['normal',3,20],['color',4,32]].map(([name,size,offset])=>({location:gl.getAttribLocation(p,name),size,offset}));for(const a of attributes)gl.enableVertexAttribArray(a.location);
 gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);
 const s=scene.summary;document.getElementById('objectCount').textContent=s.rendered_placements;document.getElementById('triangleCount').textContent=s.triangles.toLocaleString('nb-NO');document.getElementById('textureCount').textContent=s.textures;document.getElementById('modsList').textContent=s.active_mods.length?s.active_mods.join('\n'):'Ingen aktive mods';loading.textContent='Kartet er klart. Velg Utforsk Grove Street.';document.getElementById('start').textContent='Utforsk Grove Street →';document.getElementById('start').disabled=false;ready=true;
 window.saWorld={ready:true,sceneSummary:s,frames:0,lastGlError:0,position:position.slice(),batches:drawBatches.length};
 let previous=performance.now(),fpsTime=previous,fpsFrames=0;
 function draw(time){const dt=Math.min((time-previous)/1000,.05);previous=time;const enhanced=document.getElementById('lighting').value==='enhanced';
  if(menu.hidden){const speed=scene.settings.camera_speed*dt*(keys.has('shift')?4:1);const forward=[Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)],right=[-Math.cos(yaw),0,Math.sin(yaw)];let movement=[0,0,0];for(const [key,axis,sign] of [['w',forward,1],['s',forward,-1],['d',right,1],['a',right,-1],['e',[0,1,0],1],['q',[0,1,0],-1],[' ',[0,1,0],1]])if(keys.has(key))movement=movement.map((v,i)=>v+axis[i]*sign);const length=Math.hypot(...movement);if(length)position=position.map((v,i)=>v+movement[i]/length*speed);}
  const ratio=Math.min(devicePixelRatio||1,2)*Number(document.getElementById('scale').value),width=Math.max(1,Math.round(canvas.clientWidth*ratio)),height=Math.max(1,Math.round(canvas.clientHeight*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}gl.viewport(0,0,width,height);gl.depthMask(true);gl.clearColor(...scene.settings.sky_color,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
  const target=position.map((v,i)=>v+[Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)][i]);gl.uniformMatrix4fv(uniforms.mvp,false,multiply(perspective(Number(document.getElementById('fov').value)*Math.PI/180,width/height,.1,1500),lookAt(position,target)));gl.uniform3fv(uniforms.eye,position);gl.uniform3fv(uniforms.sky,scene.settings.sky_color);gl.uniform1f(uniforms.fogDistance,scene.settings.fog_distance);gl.uniform1f(uniforms.enhanced,enhanced?1:0);
  const opaque=drawBatches.filter(b=>!b.alpha),transparent=drawBatches.filter(b=>b.alpha).sort((a,b)=>dot(sub(b.center,position),sub(b.center,position))-dot(sub(a.center,position),sub(a.center,position)));
  for(const list of [opaque,transparent]){const blend=list===transparent;blend?gl.enable(gl.BLEND):gl.disable(gl.BLEND);gl.depthMask(!blend);gl.uniform1f(uniforms.cutoff,blend?.015:.45);for(const b of list){gl.bindTexture(gl.TEXTURE_2D,textures[b.texture]);gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);for(const a of attributes)gl.vertexAttribPointer(a.location,a.size,gl.FLOAT,false,48,a.offset);gl.drawArrays(gl.TRIANGLES,0,b.count);}}
  gl.depthMask(true);window.saWorld.frames++;window.saWorld.lastGlError=gl.getError();window.saWorld.position=position.slice();fpsFrames++;if(time-fpsTime>=500){document.getElementById('fps').textContent=Math.round(fpsFrames*1000/(time-fpsTime))+' FPS';fpsFrames=0;fpsTime=time;document.getElementById('coords').textContent=`X ${(position[0]+scene.center[0]).toFixed(1)} · Y ${(-position[2]+scene.center[1]).toFixed(1)} · Z ${position[1].toFixed(1)}`;document.getElementById('modeLabel').textContent=enhanced?'Enhanced test':'Classic';document.getElementById('boundary').textContent=Math.hypot(position[0],position[2])>scene.radius?'Utenfor lastet kartutsnitt':'';}
  requestAnimationFrame(draw);
 }requestAnimationFrame(draw);
}
start().catch(error=>{ready=false;loading.textContent='Kunne ikke starte visningen: '+error.message;loading.classList.add('error');console.error(error);});
