[package]
name = "sa-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
mlua = { version = "0.12.2", features = ["lua54", "vendored", "serde", "anyhow"] }
sa-net = { path = "../net" }
sa-scene = { path = "../scene" }
rmp-serde = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10.9"
ureq = { version = "3.4", default-features = false, features = ["rustls"] }
zip = { version = "4", default-features = false, features = ["deflate-flate2-zlib-rs"] }
