[package]
name = "sa-client"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
wgpu.workspace = true
glam.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sa-assets = { path = "../assets" }
sa-scene = { path = "../scene" }
sa-net = { path = "../net" }
